Document: rum
Title: Debian rum Manual
Author: <insert document author here>
Abstract: This manual describes what rum is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rum/rum.sgml.gz

Format: postscript
Files: /usr/share/doc/rum/rum.ps.gz

Format: text
Files: /usr/share/doc/rum/rum.text.gz

Format: HTML
Index: /usr/share/doc/rum/html/index.html
Files: /usr/share/doc/rum/html/*.html
