#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ -x "/etc/init.d/rum" ]; then
	if [ ! -e "/etc/init/rum.conf" ]; then
		update-rc.d rum defaults >/dev/null
	fi
	invoke-rc.d rum start || exit $?
fi
# End automatically added section
